### ISSUE TITLE
Document how users can tell whether RW catches up with the upstream PG/MySQL when using direct CDC

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#1513]
We are still testing the direct CDC for these two databases.

Once we find a good way to monitor the progress, we'll update it here.

cc: @cyliu0 @StrikeW

**Comment by hengm3467** [comment]
@lmatz Can you please summarize the changes as input for documentation update? Thank you!

**Comment by lmatz** [comment]
As shown in the screenshot in this PR: https://github.com/risingwavelabs/risingwave/pull/13877
users can monitor `consumer CDC lag latency` to determine how much RW is lagging behind the upstream table.

I suppose this is only meaningful when we are synchronizing new data in the table from the upstream database, it is not meaningful when we take the first snapshot of the table in the upstream database. Is this right? cc: @StrikeW

**Comment by StrikeW** [comment]
> As shown in the screenshot in this PR: [risingwavelabs/risingwave#13877](https://github.com/risingwavelabs/risingwave/pull/13877) users can monitor `consumer CDC lag latency` to determine how much RW is lagging behind the upstream table.
> 
> I suppose this is only meaningful when we are synchronizing new data in the table from the upstream database, it is not meaningful when we take the first snapshot of the table in the upstream database. Is this right? cc: @StrikeW

Yes, the consume lag latency only make sense for changelog instead of historical data.

For postgres (shared) source, user can execute following SQL on upstream to check the WAL lag size to determine the consumption lag.
```sql
SELECT slot_name, pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn) AS raw, pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(),restart_lsn)) AS replicationSlotLag, active FROM pg_replication_slots;
```

**Comment by StrikeW** [comment]
I'd like to draft the content here:

Right now, to observe the progress of direct CDC we have the following ways:
### For historical data
1. The historical data needs to be backfilled into Table, user can check the internal state of the backfill executor 
```
dev=> create table t3 (id integer, v1 timestamp with time zone, primary key(id)) from pg_source table 'public.t3';
CREATE_TABLE
dev=> show internal tables;
              Name
---------------------------------
 __internal_t3_3_streamcdcscan_4
 __internal_pg_source_1_source_2
(2 rows)

dev=> select * from __internal_t3_3_streamcdcscan_4;
 split_id | id | backfill_finished | row_count |                    cdc_offset
----------+----+-------------------+-----------+--------------------------------------------------
 3        |  5 | t                 |         4 | {"Postgres": {"lsn": 4558482960, "txid": 35853}}
(1 row)
```

### For new data
RisingWave will store the source offset in the internal state table of source executor. User can check the current consumed offset in the state table of the `Source` executor and compare the current log offset with the upstream database.

1. Postgres

The Postgres connector need to commit offset to upstream, so that upstream Postgres can reclaim space consumption of WAL files. The CDC source will commit offset to upstream when a checkpoint commit. If checkpoint point latency is high, the WAL on upstream will be accumulated.

User execute the following SQL on upstream Postgres to observe the accumulation of WAL.

```
SELECT slot_name, pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn) AS raw, pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(),restart_lsn)) AS replicationSlotLag, active FROM pg_replication_slots;
```

2. MySQL

User can execute the following SQL on upstream MySQL to get the current binlog offset.
```
SHOW MASTER STATUS;
```
And compare the above offset with source offset stored in the state table to determine the CDC progress.

**Comment by WanYixian** [comment]
Hi @lmatz For the content above, is it okay to add them to [PG CDC](https://docs.risingwave.com/docs/current/ingest-from-postgres-cdc/) and [MySQL CDC](https://docs.risingwave.com/docs/current/ingest-from-mysql-cdc/) separately? Or put them under optimize performance section

**Comment by lmatz** [comment]
I am thinking under PG and MySQL separately and add a link in the performance section, WDYT?
