### ISSUE TITLE
Document: feat(sink): enable kafka sink with `format plain encode protobuf`

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1611]
This issue tracks the documentation update needed for the merged PR #12858.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/12858
Source PR Merged At: 2023-10-21T07:21:34Z

**Comment by emile-00** [comment]
@xiangjinwu Is the previous syntax still supported for append-only protobuf Kafka sinks? If so, we can hold on this issue until more formats/encodes are supported.

**Comment by xiangjinwu** [comment]
Not sure what *previous syntax* refers to.

Before the linked PR, there is no support for append-only **protobuf** kafka sink. Only **json** was supported.

As mentioned in the PR, it was intentionally not labeled to update document due to limit of protocol support:
* `http[s]://` supported
* `file://` works but shall only be used for toying. Not for production use.
* `s3://` not supported yet, to avoid duplicating the bug in source that was just fixed a few days ago. https://github.com/risingwavelabs/risingwave/pull/13762
* (confluent) schema registry not supported yet https://github.com/risingwavelabs/risingwave/issues/13995
