### ISSUE TITLE
Document: feat(storage): enable preload for log store and dynamic filter

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1630]
This issue tracks the documentation update needed for the merged PR #13558.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/13558
Source PR Merged At: 2023-12-11T12:11:32Z

**Comment by neverchanje** [comment]
@Little-Wallace Please help provide the doc change that you wanted to add for the feature update.

**Comment by Little-Wallace** [comment]
This feature will make hummock could read larger in once IO operation but it will cost more memory. Since the object storage usually has large throughput and high latency for small IO operation, a larger read request will bring much higher process speed. 

The configuration `storage.prefetch_buffer_capacity_mb` represent the most memory allowed to use in prefetch. If the memory used by prefetch operation reach the limit, hummock will use the original read method for any request, which read data by block(64KB). If we set it 0, it means that this feature would be disabled. By default, it will be set with 7% of the total memory of machine.

We have reach agreement at this feature shall be enabled by default and most users do not need to change it. There are only two case that we need to change the configure  `storage.prefetch_buffer_capacity_mb`:

1. If our system meet some bug, developer may need some method to disable this feature. 
2. If the compute node use too much memory and crash because of OOM, we may need to reduce the memory usage of prefetch.
