### ISSUE TITLE
Document: feat: remove `group.id` from kafka props and reuse generated `group.id`

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1633]
This issue tracks the documentation update needed for the merged PR #13856.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/13856
Source PR Merged At: 2023-12-12T04:56:20Z

**Comment by ShanlanLi** [comment]
@neverchanje 

For removing `group.id` from kafka props, we have already moved `group_id` from our documentation since the 1.3 version. So this needs no updates in the documentation. 

For reusing the generated `group.id`, do we need documentation? Please offer some suggestions on how to write it if it's necessary.
