### ISSUE TITLE
Change required: Fix Es jsonb doc

### ISSUE THREAD

**Issue by xxhZs** [risingwavelabs/risingwave-docs-legacy#1693]
### Which part(s) of the docs might be affected or should be updated? And how?

Now, our es sink will send JSON as a JSON string, and ES will convert it into a struct structure and write it into it. So need to update docs.

jsonb  ~~text~~  =>  JSON string，ES will automatically convert it into a struct.
We need to make sure that the structure type in the json is consistent to prevent es from reporting errors

**Comment by neverchanje** [comment]
Let me eleborate on "We need to make sure that the structure type in the json is consistent to prevent es from reporting errors"

Unlike normal databases, Elasticsearch doesn't require users to explicitly CREATE TABLE. Instead, it infers the schema on-the-fly based on the first record ingested. Say, the record contains a jsonb '{v1: 100}', v1 will be inferred as a long type. However, if the next record is '{v1: "abc"}', the ingestion will fail because "abc" is inferred as string and the two types are incompatible.

This behavior should be noted in the doc, otherwise the user would be very confused why their data is less than that it should be. In terms of monitoring, users can checkout Grafana, where there is a panel for all sink write errors.
