### ISSUE TITLE
document how to configure the deployment to enable ssl/tls authentication

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1699]
### Which part(s) of the docs might be affected or should be updated? And how?

cc @chenzl25 Please help provide the detailed manual. Thanks!

**Comment by chenzl25** [comment]
# Introduction

RisingWave support using SSL connections to encrypt client/server communications.The terms SSL and TLS are often used interchangeably to mean a secure encrypted connection using a TLS protocol.

# Configuration

RisingWave has different components and SSL configuration should only be configured in the frontend nodes, since frontend nodes are responsible to communicating with clients. RisingWave frontend node would read environment variables `RW_SSL_CERT` and `RW_SSL_KEY` to load the server side SSL certificate and the private key files from the file system. For example: `RW_SSL_CERT = /path/to/cert/server.crt` and `RW_SSL_CERT = /path/to/key/server.key`.

# Creating Certificates

To create a simple self-signed certificate for the server, valid for 365 days, use the following OpenSSL command. Use 'localhost' for the 'Common name' for test purposes.

```
# Use 'localhost' for the 'Common name'
openssl req -x509 -sha256 -nodes -newkey rsa:2048 -days 365 -keyout localhost.key -out localhost.crt
```

After that you will get two files `localhost.crt` and `localhost.key` and then you can set their paths to `RW_SSL_CERT` and `RW_SSL_KEY` respectively.

Notice: While a self-signed certificate can be used for testing, it's recommended to sign the certificate through a certificate authority (CA) (usually an enterprise-wide root CA) in production.

# Verify

Clients can use psql to connect to the server with ssl request by using the following command.

```
psql -p 4566 -d dev -h localhost -U root --set=sslmode=verify-full
```

If everythings work well, you would see some information like that:

```
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
```


# Reference 

Postgresql SSL document https://www.postgresql.org/docs/current/ssl-tcp.html

**Comment by neverchanje** [comment]
Hi, @hengm3467 
I think Dylan has provided a very comprehensive guide for this topic. I've nothing to add for now. Please help refine this  draft
