### ISSUE TITLE
Document: feat: Introduce alter parallelism

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#1702]
This issue tracks the documentation update needed for the merged PR #14240.

Source PR URL: https://github.com/risingwavelabs/risingwave/pull/14240
Source PR Merged At: 2023-12-28T08:20:32Z

**Comment by ShanlanLi** [comment]
@neverchanje Hello Tao, we want to add a simple introduction to the concept "parallelism" in the topic [Key concepts and terms](https://docs.risingwave.com/docs/current/key-concepts/). Could you help draft a short paragraph to explain it? 

Or I made a draft with gpt, not sure if it's ok: 


Parallelism refers to the technique of simultaneously executing multiple database operations or queries to improve performance and increase efficiency. It involves dividing a database workload into smaller tasks and executing them concurrently on multiple processors or machines. In RisingWave, you can set the parallelism of streaming jobs, like [tables](), materialized views, and sinks.

<img width="1263" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/150168166/6def2455-fce9-495f-8669-cdacb6ba6c1e">

**Comment by neverchanje** [comment]
Will do. I plan to go through doc issues this week and next.

**Comment by ShanlanLi** [comment]
> Will do. I plan to go through doc issues this week and next.

@neverchanje Thanks very much. Please note that the topic [Key concepts and terms](https://docs.risingwave.com/docs/current/key-concepts/) has been restructured: 

<img width="924" alt="image" src="https://github.com/risingwavelabs/risingwave-docs/assets/150168166/d11295cb-167b-4c3c-bdae-e19124c2938c">


Because the old method of categorizing terms made it difficult to find appropriate placements for new terms, we have now reorganized the classification of this page. The terms on this page are now divided into two main categories: one category is related to RisingWave, and the other category consists of more general terms. Within each category, the terms are sorted alphabetically by the first letter of each word.
