### ISSUE TITLE
Clarification of when snapshots run

### ISSUE THREAD

**Issue by rotten** [risingwavelabs/risingwave-docs-legacy#1851]
### Where's the bug?

https://docs.risingwave.com/docs/current/meta-backup

### Describe the bug

It isn't clear from this document that you have to manually trigger a snapshot.  Do you?

If not, is there a way to control when or how frequently snapshots are run?

What is the best practice for snapshots?  Do they only need to be run for DDL changes, or do they need to run regularly because of new data being ingested?

**Comment by zwang28** [comment]
> It isn't clear from this document that you have to manually trigger a snapshot. Do you?

Snapshots have to be created [manually via risectl](https://docs.risingwave.com/docs/current/meta-backup/#create-a-meta-snapshot).
We'll improve the doc. Thank you.

> or do they need to run regularly because of new data being ingested?

Yes, create snapshot regularly is a practical choice. Because newer snapshot need to process less data when it's restored.

Note that the maximum number of snapshots allowed is limited to 100. So it's necessary to [delete old snapshots](https://docs.risingwave.com/docs/current/meta-backup/#delete-a-meta-snapshot) regularly.

**Comment by WanYixian** [comment]
Resolved in https://github.com/risingwavelabs/risingwave-docs/pull/1890
