### ISSUE TITLE
Document pg_catalog.pg_user

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#205]
### Related code PR

https://github.com/singularity-data/risingwave/pull/4150

### Which part(s) of the docs might be affected or should be updated? And how?

Add a system catalog/system information/system tables section.

### Reference

https://www.postgresql.org/docs/14/catalogs.html

**Comment by hengm3467** [comment]
@bernscode  As discussed with Pin, we may need to hold off making the pg_catalog functions public in our docs. This is because we are still building pieces of a bigger feature. Until that feature is fully implemented, the pieces are not that meaningful. I just removed the milestone info. We can revisit this issue sometime later.

**Comment by bernscode** [comment]
@hengm3467 Okay, that sounds good. Thanks!
