### ISSUE TITLE
Document: a dedicated page for experimental features

### ISSUE THREAD

**Issue by lmatz** [risingwavelabs/risingwave-docs-legacy#2469]
be visible to both users and us.

**Comment by fuyufjh** [comment]
The task is major motivated by @st1page's complaints: some of our new features were not 100% stabilized and cause some stability users on user's side. To mitigate this, we may mark these new features "experimental" or "preview" to remind users of the risks.

And, yes, we already have "experimental", but it's not well maintained. For example, [Subscription](https://docs.risingwave.com/docs/current/subscription/) was released recently, and I think it's probably better to be experimental for a while.

How about setting up a table for experimental features? So that the doc team can help to oversee the lifecycle of all experimental features. For example, a new feature (such as a new connector or SQL feature, small enhancements are excluded) should always be experimental when released, and the table will record the start date, so that everyone knows how long time has been since its release. 

Furthermore, I think this table can be published as a dedicated doc page. Comparing to an internal Notion page, this can hopefully make engineers focus more on this issue and also naturally make docs team to be the supervisor.

**Comment by ShanlanLi** [comment]
This is a good idea. Personally, I find it a bit difficult to decide if a feature needs an "experimental" note and when to remove that note for features that already have it, which need help from engineers. If you could provide a list of features that need to be marked as experimental, I'd be happy to create a dedicated page for them.

**Comment by lmatz** [comment]
1. https://docs.risingwave.com/docs/current/subscription/
2. https://docs.risingwave.com/docs/dev/time-travel-queries/
3. https://docs.risingwave.com/docs/dev/manage-secrets/
4. https://docs.risingwave.com/docs/dev/ingest-from-mysql-cdc/#automatically-map-upstream-table-schema

cc: @st1page

**Comment by lmatz** [comment]
> Personally, I find it a bit difficult to decide if a feature needs an "experimental" note and when to remove that note for features that already have it, which need help from engineers.

Please check with @st1page and me

Later, we will see if it can be put into some sort of procedure.
The criteria for moving a feature from `experimental` to `production-ready` is both objective and subjective. 

Right now, it is hard to put it into words.
In general:
1. if a new feature deserves a dedicated top/second-level page, it is expected to go through the "experimental" phase.
2. if it is an "advanced" improvement to an existing feature, it is expected to go through the "experimental" phase.
3. if it is a new function in SQL, we typically don't expect it to be "experimental" first.

**Comment by st1page** [comment]
> > Personally, I find it a bit difficult to decide if a feature needs an "experimental" note and when to remove that note for features that already have it, which need help from engineers.
> 
> Please check with @st1page and me

Can we do this in the current release note release process? Maybe we can comment on experimental features in the release note's notification document.

**Comment by lmatz** [comment]
good idea

**Comment by hengm3467** [comment]
We have "technical preview", "Beta" and "GA" as the maturity phases. For earliest stage, we can use "technical preview", and for preview "Beta", we can use "Public preview". @lmatz @st1page Please see this page for the current definitions: https://docs.risingwave.com/product-lifecycle/

**Comment by lmatz** [comment]
[Azure](https://azure.microsoft.com/en-us/updates), [Databricks](https://docs.databricks.com/en/release-notes/release-types.html), and [Snowflake](https://docs.snowflake.com/en/release-notes/preview-features) shared similar definitions
1. private/on-request preview
2. public/open preview
3. GA

Clickhouse uses the terminology of public beta: https://clickhouse.com/blog/clickhouse-cloud-is-now-on-azure-in-public-beta

Confluent uses "public preview": https://docs.confluent.io/cloud/current/release-notes/index.html

Also I saw people uses "preview" and "beta" interchangeably: https://help.duo.com/s/article/6720?language=en_US
![SCR-20240822-kz3](https://github.com/user-attachments/assets/4c696650-1f3e-44c6-84a1-6c10fe5c5a7a)

**Comment by lmatz** [comment]
I have no problem with beta, also agree with the meaning expressed by "technical preview" and "beta".

I just feel we can align with these modern data companies because they have a much bigger audience.
