### ISSUE TITLE
Change required: UDAF should be mentioned in UDF docs

### ISSUE THREAD

**Issue by fuyufjh** [risingwavelabs/risingwave-docs-legacy#2476]
### Related code PR

There is a [dedicated series of documents](https://docs.risingwave.com/docs/current/user-defined-functions/) for UDF, which is good. 

<img width="257" alt="image" src="https://github.com/user-attachments/assets/cd055ba6-503e-4a0e-8806-e13dd8e4301e">

However, the UDAF is never mentioned in these docs. Conceptually, UDAF is very close to UDF, or you can consider it as a subset of UDF. I think we need to merge them together.

Note that UDAF is mentioned here: https://docs.risingwave.com/docs/current/sql-create-aggregate now. Even though, according to https://github.com/risingwavelabs/risingwave-docs/issues/2442, both the reference **and** the guide should exist.

### Which part(s) of the docs might be affected or should be updated? And how?

- https://docs.risingwave.com/docs/current/user-defined-functions Needs to be enhanced with UDAF contents
- https://docs.risingwave.com/docs/current/sql-create-aggregate Needs to hyperlink to that page

**Comment by ShanlanLi** [comment]
Thanks, actually we have mentioned UDAF in the overview page by way of a toggle list:

<img width="1178" alt="image" src="https://github.com/user-attachments/assets/4aac4bc8-d7ab-410f-bd9d-78a517229717">

Because there are 3 ways to categorize UDFs. When introducing them, we chose just one to organize the information, since we feared combining the other two would make the organization confusing and unclear.

However, thanks for your feedback, this way did make it hard to find UDAFs. Now I've reorganized the information. Please feel free to tell me if there is anything that can be improved!
