### ISSUE TITLE
Document default values of the system parameters, and where to configure the values

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#660]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/8623

### Which part(s) of the docs might be affected or should be updated? And how?

Manage RisingWave -> Vieww and adjust system parameters

@Gun9niR As I understand it, we'll need to mention two things:
1. The default/initial values out of box (without customization by users)
2. Where to customize/specify the initial values

Correct? Or only the latter would be fine? 

Thanks.

**Comment by Gun9niR** [comment]
I think both are required. Some notes:

- While we can initialize the initial values from the config file (the `[system]` section), it is only for CI purposes and should not be used by the user.
- Immutable params can be initialized from CLI, e.g. `state_store` corresponds to `--state-store` and environment variable `RW_STATE_STORE`
- Mutable params can only be initialized with the default value. The user can modify it later with `ALtER SYSTEM`.

**Comment by hengm3467** [comment]
--> Immutable params can be initialized from CLI, e.g. state_store corresponds to --state-store and environment variable RW_STATE_STORE

@Gun9niR  Can you share more information about how to do this? Thanks!

**Comment by Gun9niR** [comment]
The reason that immutable params need to be initialized from CLI is due to their immutability, `ALTER SYSTEM SET` on them will fail.

So we need to initialize them from command line arguments. For example, `state_store` is one of these immutable params, so to initialize it, one can add an argument `--state-store=hummock-memory` after the **meta node command**. Once the cluster is up, the user is not allowed to change it. One can also specify the environment variable `RW_STATE_STORE` to initialize it, which overrides CLI argument. 

Once the cluster is started, the system parameters are persisted to meta store (etcd). If the meta node is restarted with different initial values for these params, they will just be ignored, and a warning message will be emitted.

**Comment by hengm3467** [comment]
Fixed in #981.
