### ISSUE TITLE
Document sink connector parameter changes

### ISSUE THREAD

**Issue by hengm3467** [risingwavelabs/risingwave-docs-legacy#666]
### Related code PR

https://github.com/risingwavelabs/risingwave/pull/8610

### Which part(s) of the docs might be affected or should be updated? And how?

@tabVersion and @xx01cyx : Could you please summarize the sink connector parameter changes in v0.1.18? I assume we'll need to update documentation to reflect the changes. 

Thanks. 

### Reference

Data delivery -> Kafka / MySQL
SQL -> CREATE SINK

**Comment by xx01cyx** [comment]
### Sink type

The following SQL is no longer valid:

```SQL
CREATE SINK si FROM t WITH (
    format = 'append_only', 
	......
);
```

Instead, the user should write:

```SQL
CREATE SINK si FROM t WITH (
    type = 'append-only',   # The "_" between "append" and "only" has been changed to "-"
	......
);
```

### Sink primary key

The user can now create an **upsert** sink with primary keys as follows:

```SQL
CREATE TABLE t (v1 int, v2 int, v3 int);
CREATE SINK si FROM t WITH (
    connector = 'xxx',
    type = 'upsert',
    primary_key = 'v1, v2',
	......
);
```

Note that this is only **valid when the external sink doesn't have its own primary key**. For example, for JDBC upsert sinks, users are not allowed to define `primary_key` because a JDBC sink has its own primary key.
