### ISSUE TITLE
Document mongdb, mysql, and postgres CDC through Debezium + Kafka

### ISSUE THREAD

**Issue by neverchanje** [risingwavelabs/risingwave-docs-legacy#894]
### Related code PR

- https://github.com/risingwavelabs/risingwave/blob/main/integration_tests/debezium-mysql/create_source.sql
- https://github.com/risingwavelabs/risingwave/blob/main/integration_tests/debezium-postgres/create_source.sql
- https://github.com/risingwavelabs/risingwave/tree/main/integration_tests/debezium-mongo/create_source.sql

### Which part(s) of the docs might be affected or should be updated? And how?

https://www.risingwave.dev/docs/current/create-source-cdc/

I guess we can make it a subfolder that contains the connection documents for debezium + mysql, debezium + postgres, and debezium + mongo.

**Comment by emile-00** [comment]
@neverchanje For now, I think it'll be better if all the information regarding CDC via Debezium type of sources is consolidated on one page. Creating subfolders may not be as helpful since we don't mention additional setup instructions on the RisingWave side. But, as we add more CDC connections in the future we may reconsider this.
